// Auto-generated by scripts/encrypt-video.ts. Do not edit manually.
export interface VideoRecord {
  id: string;
  title: string;
  manifestPath: string;
  periods: { index: number; keyId: string /* hex */ }[];
}

export const GENERATED_VIDEOS: Record<string, VideoRecord> = {
  "58fce6ff-a200-4f81-8d3c-79e1b521acbb": {
    id: "58fce6ff-a200-4f81-8d3c-79e1b521acbb",
    title: "Protected Stream (Encrypted DASH)",
    manifestPath: "58fce6ff-a200-4f81-8d3c-79e1b521acbb/manifest.mpd",
    periods: [
    {
        "index": 0,
        "keyId": "2dc0c9cd213951aeafab33901b903398"
    },
    {
        "index": 1,
        "keyId": "12238f34e09b4b66d8f809170ae690b4"
    },
    {
        "index": 2,
        "keyId": "815736fcf070bf9bafe05b128d854cb3"
    },
    {
        "index": 3,
        "keyId": "72a63c6276a5b0e3938fb84e67cb9141"
    },
    {
        "index": 4,
        "keyId": "484694a38ab9091b6c42ddb65c4d8551"
    },
    {
        "index": 5,
        "keyId": "f38fc648e61d906dd72cfa0bdc4a8608"
    },
    {
        "index": 6,
        "keyId": "75eec47e2062bb480b926a98b804c8ce"
    },
    {
        "index": 7,
        "keyId": "c2a1f648ba1bedc05566961c570077c6"
    },
    {
        "index": 8,
        "keyId": "13ead3f8114b92282a81f68b5560e05b"
    },
    {
        "index": 9,
        "keyId": "0133b56bbe1b8a5586cd7915b736ac07"
    },
    {
        "index": 10,
        "keyId": "87997e30cdc1051e9bf4146e406bf638"
    },
    {
        "index": 11,
        "keyId": "cd2bbfdda03aaf8dd38e942f79621bbd"
    },
    {
        "index": 12,
        "keyId": "59f45d8c4d90fa78805390bd6d9a9784"
    },
    {
        "index": 13,
        "keyId": "5d4dfa4f1aaf3b209de694db1610c179"
    },
    {
        "index": 14,
        "keyId": "04776004840be9acc930d5c1704e391f"
    },
    {
        "index": 15,
        "keyId": "b104908b6896a8b6d1fb2f38739438a9"
    },
    {
        "index": 16,
        "keyId": "368f5099c4360c4bc0b82f8cffc19c23"
    },
    {
        "index": 17,
        "keyId": "468a35cbf5ddefd99f44bba15f6a100e"
    },
    {
        "index": 18,
        "keyId": "373d46a77efce977e83c235114b7c50c"
    },
    {
        "index": 19,
        "keyId": "f3311b3a1d8f535ff381ad1e9ffded16"
    },
    {
        "index": 20,
        "keyId": "f2cffdb18887c180598760f9d2c9fcf6"
    },
    {
        "index": 21,
        "keyId": "3599ae130fab76d1cae73c0c449d2694"
    }
],
  },
};

export const GENERATED_KEY_STORE: Record<string, string> = {
  "2dc0c9cd213951aeafab33901b903398": "1cac858d3e5fe6d6f9cf9aea58ecb405",
  "12238f34e09b4b66d8f809170ae690b4": "c71625a5c8cea23e3c9a8cdfa0b6765e",
  "815736fcf070bf9bafe05b128d854cb3": "7e88f180b52d026fd33d3b409806ab04",
  "72a63c6276a5b0e3938fb84e67cb9141": "e5b79d27fd4d388fb4ff7566cf319925",
  "484694a38ab9091b6c42ddb65c4d8551": "d30d7530b1cee93a216c78ed856e9d6d",
  "f38fc648e61d906dd72cfa0bdc4a8608": "61206dadb82a32bbba5825d18707a573",
  "75eec47e2062bb480b926a98b804c8ce": "a46b58f0adc335ede0aeb7276a5e8cf5",
  "c2a1f648ba1bedc05566961c570077c6": "32f341ebdcb48b5481c3915d5cb26955",
  "13ead3f8114b92282a81f68b5560e05b": "0ad5e2e734b064cb9a6a8bf0ccecf31b",
  "0133b56bbe1b8a5586cd7915b736ac07": "21ad087ac824368dc8c1c026eed5fc06",
  "87997e30cdc1051e9bf4146e406bf638": "84009b0cdbec3b7fbbca669d280c9818",
  "cd2bbfdda03aaf8dd38e942f79621bbd": "63db492b66ede4c185245ae1c0134c62",
  "59f45d8c4d90fa78805390bd6d9a9784": "bfd0a311c9ad199c53838c0b55510f35",
  "5d4dfa4f1aaf3b209de694db1610c179": "fccc71b1d921d585aa7097ec11d60bb6",
  "04776004840be9acc930d5c1704e391f": "4781e074356ab95389ccb7f45d09ffb0",
  "b104908b6896a8b6d1fb2f38739438a9": "fbd4f7669292f0565e9f41ee6b5c8760",
  "368f5099c4360c4bc0b82f8cffc19c23": "4b88e72a2f91808e2e3848dfd3d1f89e",
  "468a35cbf5ddefd99f44bba15f6a100e": "b7aaef356fec8ae25ff9fe8db0c4af61",
  "373d46a77efce977e83c235114b7c50c": "a5b63dd5e1a31376d11e1363357f6089",
  "f3311b3a1d8f535ff381ad1e9ffded16": "d567fb02367a1f2f20dbdf4efdb6e39c",
  "f2cffdb18887c180598760f9d2c9fcf6": "b3c2fef40c6a239df660e317b9dba4fb",
  "3599ae130fab76d1cae73c0c449d2694": "fece2fcd6433d1d6295fdf0bed5ca4cd",
};

export const GENERATED_DEFAULT_VIDEO_ID = "58fce6ff-a200-4f81-8d3c-79e1b521acbb";
